### PR TITLE
feat: add anchors to headings to support deep linking

### PR DESCRIPTION
**Pull request by pavanjadhaw**
## Change description

We already had [rehype-autolink-headings](https://github.com/rehypejs/rehype-autolink-headings) and [rehype-slug](https://github.com/rehypejs/rehype-slug) plugin configured which automatically adds links to headings but the option to wrap heading was not provided.  
For what @smeijer described `'wrap'` works best but there are other behaviour options as well `'prepend', 'append', 'before', 'after'` we could go with depending on what we are looking for.

Since headings are now wrapped inside anchor we might have to tweak the heading color a little.

https://user-images.githubusercontent.com/26551780/143649815-5b2189ca-37a6-4ad1-a5a6-3ac5e29c1100.mp4

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> Implements [#37](https://github.com/magicbell-io/docs/issues/37) 

### Development

- [x] Lint rules pass locally
- [x] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

### CODE REVIEW

**Comment by smeijer** [comment]
Hi @pavanjadhaw,

Thanks for this contribution. Unfortunately, I can't merge it like this, because the title moves behind the navbar in the current implementation. Although it's still useful for you and me, it will be confusing to most users.

Do you see a chance to improve that?

**Comment by pavanjadhaw** [comment]
Thank you so much @smeijer, I will add the above improvements (I didn't know about scroll-margin property :P)
I will check why it's not working for REST and GraphlQL API pages

**Comment by pavanjadhaw** [comment]
Hey @smeijer, I made suggested changes and those work great. The auto-linking of headings was not working as plugins were not specified for those routes. I added it to all the routes now.

Is there a way to improve this code since we are duplicating it at many places?

**Comment by smeijer** [comment]
This is looking great! One last thing though, not all headings seem to be handled? Take the graphql page: [preview link](https://docs-e3m7j2m0s-magicbell.vercel.app/docs/graphql-api/reference#other-operations)

| tag | title               | state        |
|-----|---------------------|---------------|
| h2  | authentication      | clickable     |
| h3  | admin operations    | clickable     |
| h2  | fetch notifications | not clickable |

**Comment by pavanjadhaw** [comment]
The api reference is generated from `shema.graphql` and we are not using mdx for that. We are using custom components for rendering api doc.

I think we can manually wrap these in anchor tag with proper slug.

https://github.com/magicbell-io/docs/blob/dd46fb523d6ef2ae9b22a57f93d7f9e889bc18f8/src/components/graphql/Field.tsx#L25

**Comment by smeijer** [comment]
Sounds good :+1: . We just need to generate a slug, and give them the same structure & style as the generated ones.

```js
import slugify from 'slugify';
const slug = slugify(heading, { lower: true, remove: /\"\|\?/ });
```

Snippet extracted from: https://github.com/magicbell-io/docs/blob/5c1e58a749c567dec7cde72a7b1010b95a7e9a0d/scripts/build-search-index.mjs#L146-L148

**Comment by pavanjadhaw** [comment]
I just tried it and confirming that it works, I will make the necessary changes. 

https://user-images.githubusercontent.com/26551780/144205995-475ca359-faec-4626-94c2-d61645e512a0.mp4

**Review by smeijer — APPROVED** [review]
Looking Good :sunglasses: . Thanks so much!

**Comment by smeijer** [comment]
This is now running on production. Thanks again!

**Comment by pavanjadhaw** [comment]
I will keep an eye on any new open issues, if there's anything else you think I could pick up do let me know. 😎

**Pull request merged**
